# Generated by Django 4.1.3 on 2023-01-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_appointmentform_sd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='css_status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
