# Generated by Django 4.1.3 on 2023-01-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_appointmentform_css_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssform',
            name='department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
